export const db = {
  averageTrainingData: [
    {
      type: 'time',
      count: 80,
      increment: 20,
      title: '평균 인지 훈련 시간',
      iconSrc: '/card/cognitive.svg',
    },
    {
      type: 'time',
      count: 80,
      increment: 70,
      title: '평균 명상 시간',
      iconSrc: '/card/meditation.svg',
    },
    {
      type: 'time',
      count: 80,
      increment: 30,
      title: '평균 운동 시간',
      iconSrc: '/card/running.svg',
    },
    {
      type: 'count',
      count: 2,
      increment: -3,
      title: '평균 운동 횟수',
      iconSrc: '/card/running.svg',
    },
    {
      type: 'count',
      count: 0,
      increment: -3,
      title: '평균 식사 기록 횟수',
      iconSrc: '/card/meal.svg',
    },
    {
      type: 'time',
      count: 80,
      increment: 20,
      title: '평균 수면 시간',
      iconSrc: '/card/sleep.svg',
    },
    {
      type: 'count',
      count: 7,
      increment: 3,
      title: '평균 메모 기록 횟수',
      iconSrc: '/card/memo.svg',
    },
  ],
  profile: {
    nickname: '김진혁',
    age: 28,
    isMale: true,
    birthOfDate: 20,
    birthOfMonth: 6,
    birthOfYear: 1995,
    contact: '010-9590-2033',
    uid: 'ABCDEFGHIJKLMN',
  },
  meetings: [
    {
      id: 1,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: 'pdf',
      fileSize: '164KB',
    },
    {
      id: 2,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: 'pdf',
      fileSize: '164KB',
    },
    {
      id: 3,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: null,
      fileSize: '164KB',
    },
    {
      id: 4,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: null,
      fileSize: '164KB',
    },
    {
      id: 5,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: 'image',
      fileSize: '164KB',
    },
    {
      id: 6,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: 'image',
      fileSize: '164KB',
    },
    {
      id: 7,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: 'image',
      fileSize: '164KB',
    },
    {
      id: 8,
      date: '2022.11.11',
      time: '오전 09:00 - 오전 10:00',
      title: '{sessionType} | {session round N}',
      fileFormat: 'image',
      fileSize: '164KB',
    },
  ],
};
